[toolchain]
channel = "esp"
components = ["rust-src"]
targets = ["riscv32imac-unknown-none-elf"]

# channel = "stable"
# components = ["rust-src"]
# targets = [
#     "riscv32imc-unknown-none-elf",  # ESP32-C3
#     "riscv32imac-unknown-none-elf", # ESP32-C6, ESP32-H2
# ]
